### PR TITLE
fix lib name

### PR DESCRIPTION
**Pull request by tdinesh**

### CODE REVIEW

**Comment by ljarin** [comment]
Can this be merged? Just wasted some time with a student today rediscovering this bug

**Comment by tdinesh** [comment]
> Can this be merged? Just wasted some time with a student today rediscovering this bug @tdinesh @jakewelde

Added you as a reviewer. Can you approve?

**Review by ljarin — APPROVED** [review]
Tested

**Review by jakewelde — APPROVED** [review]
Really sorry I dropped the ball on this, sorry @ljarin for the wasted time. Yes this can be merged.

**Comment by ljarin** [comment]
No worries, also PTAL at https://github.com/KumarRobotics/multi_mav_manager/pull/8 if you can

**Pull request merged**
