### PR TITLE
Failsafe for nan throttle bug

### PR DESCRIPTION
**Pull request by jmcwil**
Failsafe I am using to ensure that the edge case hit in #142 does not result in the robot going full throttle when the position command is nan. min(1.0, nan)  = 1.0 so we want to ensure we check for when throttle is nan. Now the robot will set throttle to 0.0 if it hits this edge case.

### CODE REVIEW

**Review by kartikmohta — APPROVED** [review]

**Comment by versatran01** [comment]
Out of curiosity, where does this nan come from exactly?
The silent nan seems to be causing a lot of issues. Maybe there should be checks at the beginning of each critical function to ensure that input is not nan.

**Comment by jmcwil** [comment]
In my experience it only happens during the calculations in traj_gen for
certain matrices as detailed in issue #142. A better solution would
probably be to check for it in traj_gen and perhaps recalculate with a
slightly perturbed initial position of the robot so that it does not result
in the nan value. I am not very familiar with the computation in that
function, however.

**Comment by versatran01** [comment]
@kartikmohta Is there a reference to this piece of code in traj_gen.cpp?
It seems like the nan is coming from `A` being rand-deficient?
and since Eigen::PartialPivLU is not numerically stable for this case, it creates nan.
https://eigen.tuxfamily.org/dox/classEigen_1_1PartialPivLU.html
> Typically, partial pivoting LU decomposition is only considered numerically stable for square invertible matrices. 

There are two potential fixes to this
1. as suggested by @jmcwil, we could add some kind of perturbation to make sure ``A is full rank.
2. or we can just use fullPivLU instead https://eigen.tuxfamily.org/dox/classEigen_1_1FullPivLU.html
This godbolt link shows that fullPivLU does not produce nans.
https://godbolt.org/z/avhPfY6Wa

**Comment by jmcwil** [comment]
@versatran01 I would caution against swapping for fullPivLU. I previously attempted this and it qualitatively seemed to negatively affect the other planned trajectories for some reason. Although perhaps in the case that partialPivLU creates nan then fullPivLU could be used. I did not try that.

**Comment by versatran01** [comment]
After a bit of search, I realize that fullPivLU also permutes the column, that's probably why it is not being used.

**Comment by kartikmohta** [comment]
@versatran01 The traj_gen.cpp implementation mostly follows this paper: https://groups.csail.mit.edu/rrg/papers/Richter_ISRR13.pdf

Sorry I won't be able to test this any time soon, but can you guys check if any of the segment times in `TrajectoryGenerator::calculate` are close to 0 or very small (< 0.1sec)? Handling this in the problem construction is probably easier than trying to get the linear algebra to work with rank-deficient matrices.

**Comment by versatran01** [comment]
I don't know how to test this, but 0.1s doesn't seem like a very small time, why would it cause trouble?
Maybe add a check to make sure that `waypoint_times` is sorted?

**Comment by kartikmohta** [comment]
> I don't know how to test this

Just print the `seg_time` in `TrajectoryGenerator::calculate` and see if it is too small for any segment.

> 0.1s doesn't seem like a very small time, why would it cause trouble?

The `seg_time` is potentially raised to the 5th or 6th power in the computation, so 0.1 sec was just some small time that I chose which should be larger than typical segment times. The actual threshold can be a bit smaller I guess.

**Pull request merged**
